[colors.primary]
background = "#0d1926"
foreground = "#b4e1fd"

[colors.cursor]
text = "#0d1926"
cursor = "#b4e1fd"

[colors.selection]
text = "#0d1926"
background = "#b4e1fd"

[colors.normal]
black   = "#363636"
red     = "#ff0883"
green   = "#83ff08"
yellow  = "#ff8308"
blue    = "#0883ff"
magenta = "#8308ff"
cyan    = "#08ff83"
white   = "#b6b6b6"

[colors.bright]
black   = "#424242"
red     = "#ff1e8e"
green   = "#8eff1e"
yellow  = "#ff8e1e"
blue    = "#1e8eff"
magenta = "#8e1eff"
cyan    = "#1eff8e"
white   = "#c2c2c2"
